### ISSUE TITLE
Deprecation of WifiClientSecure

### ISSUE THREAD

**Issue by jack-kenney** [witnessmenow/arduino_twitch_api#1]
WifiClientSecure has been deprecated since May 13, and replaced by WifiClientSecureBearSSL. Usage of the Arduino Twitch API requires the legacy WifiClientSecure. 

According to [WifiClientSecureBearSSL.h,](https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.h) in order to use the legacy library, some changes must be made to the final sketch:

`#define USING_AXTLS`
`#include <ESP8266WiFi.h>`
`//#include <WiFiClientSecure.h>`
`#include "WiFiClientSecureAxTLS.h"`
`using namespace axTLS;`

I encountered this issue today. After much troubleshooting, and eventually switching to the legacy library, I was able to successfully connect to the Twitch API.

**Comment by witnessmenow** [comment]
You can also use that Wificlientsecure and just add client.setInsecure();
somewhere in the setup

**Comment by jack-kenney** [comment]
Gotcha, thanks for that. I'm new to this sort of thing and it took me ages to get it sorted out.
